apiVersion: v1
kind: Pod
metadata:
  name: jvm-stats6
  namespace: default
spec:
  containers:
  - image: docker.io/library/jvm-stats:1.0
    imagePullPolicy: IfNotPresent
    name: jvm-stats6
    resources:
      requests:
        cpu: 1000m
        memory: 2Gi
      limits:
        cpu: 1000m
        memory: 2Gi
    ports:
      - containerPort: 8081
        name: server
    args:
      - "-XX:ActiveProcessorCount=4"
      - "-XX:MaxRAMPercentage=75"
      - "-XX:+UseZGC"
      - "-XX:+ZGenerational"
      - "-jar"
      - "/app/jvm-stats.jar"